### ISSUE TITLE
add code of conduct file

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/leetcode_solved_programs#1]
Description:

Add code_of_conduct file. refer https://github.com/jsvigneshkanna/tailwind_ui_components 

Please star the repo to make this repo cooler 😎

**Comment by deek121477** [comment]
Can I work on this issue?

**Comment by jsvigneshkanna** [comment]
Yes @deek121477 please star the repo

**Comment by slashgk** [comment]
I can work on it.

**Comment by slashgk** [comment]
PR: https://github.com/jsvigneshkanna/leetcode_solved_programs/pull/17
