### ISSUE TITLE
Add contributing guide

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/leetcode_solved_programs#11]
Add a new contributing guide
Refer - https://github.com/jsvigneshkanna/tailwind_ui_components

Modify as per this repo. Please star the repo

**Comment by aryanprince** [comment]
Could I work on this?

**Comment by jsvigneshkanna** [comment]
@aryanprince , let's wait for some time for others to take this issue. If not assigned you can work on it

**Comment by jsvigneshkanna** [comment]
@aryanprince  assigning to your name
