### ISSUE TITLE
Add stylized scroll bar

### ISSUE THREAD

**Issue by developer-diganta** [jsvigneshkanna/leetcode_solved_programs#15]
![image](https://user-images.githubusercontent.com/65999534/198943914-c8d54697-8789-4243-9062-f1bb0af1625e.png)
The scroll bar can be stylized according to theme. If this seems legit, can I work on it?

**Comment by jsvigneshkanna** [comment]
@developer-diganta , great idea.

We can use the existing colour palette. Will like to see the PR.
Also, star the repo, to make it cooler

**Comment by jsvigneshkanna** [comment]
@developer-diganta , if you have any other features which we can implement in this project let me know

**Comment by developer-diganta** [comment]
Sure!

**Comment by jsvigneshkanna** [comment]
@developer-diganta , also check - https://github.com/jsvigneshkanna/tailwind_ui_components/ whether we can add same feature there too
