### ISSUE TITLE
Update Readme Badges

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/leetcode_solved_programs#20]
### Bug Title

Update Readme Badges

### Description of BUG

Make the below badges flex flex-row

### Bug Issue Type

Documentation

### Screenshot of the issue if in UI/ Document

![image](https://user-images.githubusercontent.com/42484705/199030232-45ce0286-52e9-4a5d-bbf7-d4af0b6a4516.png)

### Are you taking this issue fix

No

**Comment by BoshraJaber** [comment]
@jsvigneshkanna I would like to help 😊

**Comment by jsvigneshkanna** [comment]
@BoshraJaber , please go ahead. Dont forget to star the repo

**Comment by aryanprince** [comment]
@jsvigneshkanna @BoshraJaber Sorry didn't notice this issue, fixed this as a part of #21
