### ISSUE TITLE
Add new PR template

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/leetcode_solved_programs#24]
### Bug Title

Add new PR template

### Description of BUG

Add new PR template
refer - https://github.com/jsvigneshkanna/tailwind_ui_components

Don't forget to star the Repository

**Comment by jessicaribeiroalves** [comment]
Hi @jsvigneshkanna 
Can I work on this?

**Comment by jsvigneshkanna** [comment]
@jessicaribeiroalves , sure please go ahead

Dont forget to star the rep
