### ISSUE TITLE
Add buymecoffee section in readme

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/leetcode_solved_programs#8]
Add buy me a coffee section in the readme.
Refer - https://github.com/jsvigneshkanna/tailwind_ui_components

Star the repo to make it cooler

**Comment by aryanprince** [comment]
Sounds simple, I'll get started on this?

**Comment by jsvigneshkanna** [comment]
Hi @aryanprince , please go ahead.

Can we wait for others to take the other issues. If they are not assigned afternoon, I will assign them to your name

**Comment by aryanprince** [comment]
Sure, no worries!
