### ISSUE TITLE
Add bug issue template

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/leetcode_solved_programs#9]
Add bug issue template for the repo 
Refer -https://github.com/jsvigneshkanna/tailwind_ui_components

Please star the repo to make it cooler

**Comment by developer-diganta** [comment]
Can I work on this?

**Comment by jsvigneshkanna** [comment]
Sure @developer-diganta

**Comment by developer-diganta** [comment]
Shall I make it the same as Tailwind UI components one?

**Comment by jsvigneshkanna** [comment]
yes @developer-diganta
